@baseUrl = https://<your-api-management-service-name>.azure-api.net

@apimSubscriptionKey = <your-subscription-key>  # Leave empty for no subscription key

##############################################
# rate-limit API 1
##############################################

GET {{baseUrl}}/rate-limit-1/operation-1
Ocp-Apim-Subscription-Key: {{apimSubscriptionKey}}

###

GET {{baseUrl}}/rate-limit-1/operation-2
Ocp-Apim-Subscription-Key: {{apimSubscriptionKey}}

###

GET {{baseUrl}}/rate-limit-1/operation-3
Ocp-Apim-Subscription-Key: {{apimSubscriptionKey}}


##############################################
# rate-limit API 2
##############################################

GET {{baseUrl}}/rate-limit-2/operation-1
Ocp-Apim-Subscription-Key: {{apimSubscriptionKey}}

###

GET {{baseUrl}}/rate-limit-2/operation-2
Ocp-Apim-Subscription-Key: {{apimSubscriptionKey}}

###

GET {{baseUrl}}/rate-limit-2/operation-3
Ocp-Apim-Subscription-Key: {{apimSubscriptionKey}}


##############################################
# rate-limit-by-key API 1
##############################################

GET {{baseUrl}}/rate-limit-by-key-1/operation-1
Ocp-Apim-Subscription-Key: {{apimSubscriptionKey}}

###

GET {{baseUrl}}/rate-limit-by-key-1/operation-2
Ocp-Apim-Subscription-Key: {{apimSubscriptionKey}}

###

GET {{baseUrl}}/rate-limit-by-key-1/operation-3
Ocp-Apim-Subscription-Key: {{apimSubscriptionKey}}


##############################################
# rate-limit-by-key API 2
##############################################

GET {{baseUrl}}/rate-limit-by-key-2/operation-1
Ocp-Apim-Subscription-Key: {{apimSubscriptionKey}}

###

GET {{baseUrl}}/rate-limit-by-key-2/operation-2
Ocp-Apim-Subscription-Key: {{apimSubscriptionKey}}

###

GET {{baseUrl}}/rate-limit-by-key-2/operation-3
Ocp-Apim-Subscription-Key: {{apimSubscriptionKey}}


##############################################
# rate-limit via fragment API
##############################################

GET {{baseUrl}}/rate-limit-via-fragment/operation-1
Ocp-Apim-Subscription-Key: {{apimSubscriptionKey}}

###

GET {{baseUrl}}/rate-limit-via-fragment/operation-2
Ocp-Apim-Subscription-Key: {{apimSubscriptionKey}}

###

GET {{baseUrl}}/rate-limit-via-fragment/operation-3
Ocp-Apim-Subscription-Key: {{apimSubscriptionKey}}
