@baseUrl = https://<your-api-management-service-name>.azure-api.net


##############################################
# rate-limit API 1
##############################################

GET {{baseUrl}}/rate-limit-1/operation-1

###

GET {{baseUrl}}/rate-limit-1/operation-2

###

GET {{baseUrl}}/rate-limit-1/operation-3


##############################################
# rate-limit API 2
##############################################

GET {{baseUrl}}/rate-limit-2/operation-1

###

GET {{baseUrl}}/rate-limit-2/operation-2

###

GET {{baseUrl}}/rate-limit-2/operation-3
