@baseUrl = https://<your-api-management-service-name>.azure-api.net


### BACKEND API TESTS

# Get 200 OK from Backend API directly
GET {{baseUrl}}/backend/200

###

# Get 500 Internal Server Error from Backend API directly
GET {{baseUrl}}/backend/500



### DEFAULT ERROR HANDLING TESTS

# A 404 is returned by the Backend API - Should return a 404 with default error handling
GET {{baseUrl}}/frontend/default-behaviour/404

###

# A 401 is returned by the Backend API - Should return a 500 with default error handling
GET {{baseUrl}}/frontend/default-behaviour/401



### ERROR HANDLED TESTS

# A 404 is returned by the Backend API - Should return a 404 when error is handled by operation and no custom error handling is defined
GET {{baseUrl}}/frontend/error-handled/404

###

# A 401 is returned by the Backend API - Should return a 401 when error is handled by operation and no custom error handling is defined
GET {{baseUrl}}/frontend/error-handled/401